### PR TITLE
remove warnings

### PR DESCRIPTION
**Pull request by pikorkar**
@ViolanteCodes I removed some dependency warnings. But for loding enviroment variables from .env file I am using @ngx-env/builder package and it is causing 5 high severity vulnerabilities. I tried load variables using dotenv package, but I wasn't successful. I am sorry, I don't know which other package to use.

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@pikorkar Is this the process you used to try to load with dotenv?  https://javascript.plainenglish.io/setup-dotenv-to-access-environment-variables-in-angular-9-f06c6ffb86c0

**Comment by ViolanteCodes** [comment]
@pikorkar Or was it one of these? https://indepth.dev/tutorials/angular/inject-environment-variables

**Comment by pikorkar** [comment]
> @pikorkar Is this the process you used to try to load with dotenv? https://javascript.plainenglish.io/setup-dotenv-to-access-environment-variables-in-angular-9-f06c6ffb86c0

Yes, I tried this to load dotenv, but i got some errors with Webpack 5.

> @pikorkar Or was it one of these? https://indepth.dev/tutorials/angular/inject-environment-variables

Then I tried the package from this link (@ngx-env/builder) and I am using it now, but it has some vulnerabilities.

**Comment by pikorkar** [comment]
@ViolanteCodes I managed to remove all vulnerabilities from packages and implemented dotenv to load it.

**Pull request merged**
